uhh.. The previous release had a load problems: The executable wont start: FIXED
NoClassDefFoundError : FIXED
no main class set : FIXED

It turns out we have to manually edit pom.xml file to correctly build the executable lol